name: sena_portfolio
description: "Sena Şahin - Kişisel Portfolyo Web Sitesi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
    - assets/profile.png
